name: Compilar DSK SFz Player

on:
  workflow_dispatch:
    inputs:
      build_windows:
        description: 'Compilar para Windows'
        required: true
        default: true
        type: boolean
      build_macos:
        description: 'Compilar para macOS'
        required: true
        default: true
        type: boolean
      build_linux:
        description: 'Compilar para Linux'
        required: true
        default: true
        type: boolean

jobs:
  build-windows:
    if: ${{ inputs.build_windows }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Configurar y Compilar
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: DSK-SFz-Player-Windows
          path: build/**/*VST3*

  build-macos:
    if: ${{ inputs.build_macos }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Configurar y Compilar
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: DSK-SFz-Player-macOS
          path: build/**/*VST3*

  build-linux:
    if: ${{ inputs.build_linux }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Instalar dependencias
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libx11-dev libxcursor-dev libxinerama-dev libxext-dev libfreetype6-dev libxrandr-dev libxcomposite-dev libxrender-dev
      - name: Configurar y Compilar
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: DSK-SFz-Player-Linux
          path: build/**/*VST3*